In [1]:
import sys
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install scikit-learn

Requirement already satisfied: pandas in /Users/hertzg/miniconda3/lib/python3.10/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/hertzg/miniconda3/lib/python3.10/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /Users/hertzg/miniconda3/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /Users/hertzg/miniconda3/lib/python3.10/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /Users/hertzg/miniconda3/lib/python3.10/site-packages (from pandas) (1.24.2)
Requirement already satisfied: six>=1.5 in /Users/hertzg/miniconda3/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: scikit-learn in /Users/hertzg/miniconda3/lib/python3.10/site-packages (1.3.0)
Requirement already satisfied: numpy>=1.17.3 in /Users/hertzg/miniconda3/lib/python3.10/site-packages (from scikit-learn) (1.24.2)
Requirement already satisfied: scipy>=1.5.0 in /Users/hertzg/miniconda3/lib/python3.10/site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /Users/hertzg/miniconda3/lib/python3.10/site-packages (from scikit-learn) (1.3.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Users/hertzg/miniconda3/lib/python3.10/site-packages (from scikit-learn) (3.2.0)

In [2]:
import json
import pandas as pd

In [3]:
products = pd.read_json('../data/products.json')
maklers = pd.read_json('../data/maklers.json')
floors = pd.read_json('../data/floors.json')
users = pd.read_json('../data/users.json')
points = pd.read_json('../data/mapData_points.json')

In [4]:
#products.head()
columns = filter(lambda col: not col.endswith('_json'), products.columns) 
clean_products = products[columns].set_index('product_id')
clean_products.head()

,user_id,parent_id,makler_id,has_logo,makler_name,loc_id,street_address,yard_size,yard_size_type_id,submission_id,...,bedrooms,floor,parking_id,canalization,water,road,electricity,owner_type_id,osm_id,homeselfie
product_id,,,,,,,,,,,,,,,,,,,,,
12619206,2386006,NaN,NaN,NaN,None,738,,0,0,NaN,...,1,8,0,0,0,0,0,1,642934563,0
15669957,926993,NaN,NaN,NaN,None,849,არჩილ მეფის 8გ,0,0,NaN,...,1,2,2,0,0,0,0,1,442570157,0
14709424,4344680,NaN,NaN,NaN,None,1519,წყალტუბოს 12,0,0,NaN,...,1,2,0,0,0,0,0,1,140357424,0
15783255,816227,NaN,NaN,NaN,None,825,,0,1,NaN,...,1,1,0,0,0,0,0,1,542807704,0
10843675,4051279,NaN,NaN,NaN,None,741,სპორტის სასახლის უკან 598994545,0,0,NaN,...,1,14,0,0,0,0,0,1,648652633,0

In [5]:
maklers.head()

Empty DataFrame
Columns: []
Index: []

In [6]:
#floors.head()
clean_floors = floors[['developer_flat_id', 'product_id','floor','price','price_value','currency_id']].set_index('product_id')
clean_floors.head()

            developer_flat_id  floor  price  price_value  currency_id
product_id
9737899                 32018     10   60.0         60.0            3
10843675               790303     14   80.0         80.0            3
11645082              1591840      4   30.0         30.0            3
12294204              2241082     14  100.0        100.0            3
12619206              2566304      8   40.0         40.0            3

In [7]:
#users.head()
clean_users = users[['user_id', 'username', 'gender_id']].set_index('user_id')
clean_users.head()

                        username  gender_id
user_id
816227    msharashidze@yahoo.com          2
926993   natipopkhadze@gmail.com          2
1801257  ekakozhoridze@yahoo.com          2
2070890   eka_jachvliani@mail.ru          2
2255274     e.davladze@yahoo.com          2

In [8]:
#points.head()
clean_points = points[['product_id', 'title', 'owner_type', 'href']]
clean_points = clean_points \
    .join(points['price'].apply(pd.Series)) \
    .join(points['center'].apply(pd.Series)) \
    .set_index('product_id')
clean_points.head()

,title,owner_type,href,amount,currency,lat,lng
product_id,,,,,,,
12619206,ქირავდება დღიურად ახალი აშენებული ბინა,მესაკუთრე,https://www.myhome.ge/ka/pr/12619206/qiravdeba...,40,₾,41.7279282,44.7680255
15669957,იყიდება ახალი აშენებული ბინა,მესაკუთრე,https://www.myhome.ge/ka/pr/15669957/iyideba-a...,"155,100",₾,41.7925166,44.7395589
14709424,ქირავდება დღიურად ახალი აშენებული ბინა,მესაკუთრე,https://www.myhome.ge/ka/pr/14709424/qiravdeba...,50,₾,41.744776901984835,44.77654525065668
15783255,ქირავდება ძველი აშენებული ბინა,მესაკუთრე,https://www.myhome.ge/ka/pr/15783255/qiravdeba...,"1,360",₾,41.7297185,44.7685213
10843675,ქირავდება დღიურად ახალი აშენებული ბინა,მესაკუთრე,https://www.myhome.ge/ka/pr/10843675/qiravdeba...,80,₾,41.7198534,44.7780999

In [9]:
full = clean_products \
    .join(clean_floors, rsuffix='_floor') \
    .join(clean_users, on='user_id', rsuffix='_user') \
    .join(clean_points, rsuffix='_point') \
    .drop_duplicates()
full.head()

,user_id,parent_id,makler_id,has_logo,makler_name,loc_id,street_address,yard_size,yard_size_type_id,submission_id,...,currency_id_floor,username,gender_id,title,owner_type,href,amount,currency,lat,lng
product_id,,,,,,,,,,,,,,,,,,,,,
7156153,1938385,NaN,NaN,NaN,None,647,სიმონ კანდელაკის ქ.,0,0,0.0,...,3,dato.zaalishvili.81@mail.ru,1,ქირავდება დღიურად ახალი აშენებული ბინა,აგენტი,https://www.myhome.ge/ka/pr/7156153/qiravdeba-...,200,₾,41.7245209,44.7537885
7501716,3005755,3005755.0,2643.0,0.0,S A N D O,675,,2000,1,0.0,...,1,maka.777uchava@gmail.com,2,ქირავდება აგარაკი,აგენტი,https://www.myhome.ge/ka/pr/7501716/qiravdeba-...,"5,220",₾,41.6939085,44.6936625
7613770,1844883,NaN,NaN,NaN,None,696,Metrostan,0,0,0.0,...,1,lovageorkian@gmail.com,2,იყიდება მიწის ნაკვეთი მშენებლობისთვის,აგენტი,https://www.myhome.ge/ka/pr/7613770/iyideba-mi...,"731,000",₾,41.6988174,44.8818285
7885912,1576468,1576468.0,7406.0,1.0,REAL MARKET,643,მთაწმინდა,0,0,NaN,...,1,t.marsagishvili@mail.ru,1,ქირავდება ახალი აშენებული ბინა,აგენტი,https://www.myhome.ge/ka/pr/7885912/qiravdeba-...,"5,220",₾,41.6964053,44.7938526
8141073,1576468,1576468.0,7406.0,1.0,REAL MARKET,647,ლისი ვერანდა,0,0,NaN,...,1,t.marsagishvili@mail.ru,1,ქირავდება ახალი აშენებული ბინა,აგენტი,https://www.myhome.ge/ka/pr/8141073/qiravdeba-...,"5,740",₾,41.7245209,44.7537885

In [10]:
ConditionIDs = {1:"ახალი გარემონტებული",5:"სარემონტო",6:"ძველი გარემონტებული"}
AreaSizeTypeIDs = {1:"მ2",2:"1/100"}
YardSizeTypeIDs = {1:"მ2",2:"1/100",3:"ჰა"}
Roomss = {1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",7:"7",8:"8",9:"9",10:"10"}
BedRoomss = {1:"1",2:"2",3:"3",4:"4",5:"5",6:"6",7:"7",8:"8",9:"9",10:"10"}
BathRoomss = {1:"1",2:"2",3:"3+",4:"საერთო"}
LivingRoomTypes = {1:"გამოყოფილი",2:"სტუდიო"}
BalconyTypes = {1:"ღია",2:"დახურული"}
StoreTypeIDs = {1:"სარდაფი",2:"სხვენი",3:"საკუჭნაო",4:"გარე სათავსო",5:"საერთო სათავსო"}
ParkingIDs = {0:"ეზოს პარკინგი",1:"ავტოფარეხი",2:"პარკინგის ადგილი",3:"მიწისქვეშა პარკინგი",4:"ფასიანი ავტოსადგომი"}
HotWaterIDs = {1:"გაზის გამაცხელებელი",2:"ავზი",3:"დენის გამაცხელებელი",4:"ბუნებრივი ცხელი წყალი",5:"მზის გამათბობელი",6:"ცენტრალური გათბობის სისტემა"}
WarmingIDs = {2:"ცენტრალური გათბობა",3:"გაზის გამათბობელი",4:"დენის გამათბობელი",5:"იატაკის გათბობა"}
ProductTypeID = {1:"კორპუსის ბინა",2:"სახლი და აგარაკი",4:"კომერციული ფართი",5:"მიწის ნაკვეთი",7:"სასტუმრო"}
estate_type_id = {1: 'ახალი აშენებული', 2: 'მშენებარე', 3: 'ძველი აშენებული', 4: 'საოფისე', 5: 'სავაჭრო', 6: 'სასაწყობე', 7: 'საწარმოო ფართი', 8: 'უნივერსალური', 9: 'სპეციალური', 10: 'კვების ობიექტები', 12: 'ავტოფარეხი', 13: 'სასოფლო სამეურნეო', 14: 'არა სასოფლო სამეურნეო', 15: 'კომერციული', 16: 'სპეციალური', 17: 'სახლი', 18: 'აგარაკი', 19: 'სარდაფი', 20: 'ნახევარსარდაფი', 21: 'საინვესტიციო/მშენებლობისთვის', 22: 'მთლიანი შენობა', 23: 'ავტოსამრეცხაო', 521: 'ავტოსერვისი'}
AdTypeID = {1:"იყიდება",2:"გირავდება",3:"ქირავდება",7:"ქირავდება დღიურად",8:"გაიცემა იჯარით"}
HasFurnitureAndTechnic = {1:"კი",2:"არა"}
currency_ids = {1: 'USD', 2: 'EUR', 3: 'GEL'}
SpecialPersons = {1:"შშმპ ადაპტირებული"}
LivingRoom = {1:"მისაღები"}
Loggia = {1:"ლოჯი"}
Balcony = {1:"ბალკონი"}
Veranda = {1:"აივანი"}
StoreType = {183:"სათავსო"}
FirePlace = {184:"ბუხარი"}
Cellar = {1:"მარანი"}
Pool = {1:"აუზი"}
Gas = {1:"ბუნებრივი აირი"}
Alarm = {342:"სიგნალიზაცია"}
Internet = {410:"ინტერნეტი"}
Water = {423:"წყალი"}
Canalization = {424:"კანალიზაცია"}
Electricity = {1:"ელექტროენერგია"}
Television = {444:"ტელევიზია"}
Telephone = {1:"ტელეფონი"}
TV = {2:"ტელევიზორი"}
Conditioner = {3:"კონდიციონერი"}
Refrigerator = {358:"მაცივარი"}
WashingMachine = {359:"სარეცხი მანქანა"}
Dishwasher = {360:"ჭურჭლის სარეცხი მანქანა"}
Curry = {361:"ქურა (გაზის/ელექტრო)"}
Furnace = {362:"ღუმელი"}
Furniture = {363:"ავეჯი"}
ForChange = {"on":"შესაძლებელია გაცვლა"}
ChangeType = {1:"მიწის ნაკვეთი",2:"სახლი",3:"ბინა",4:"კომერციული ფართი",5:"ავტომობილი"}
PromBlockOrderValue = {10:"VIP",15:"VIP+",20:"Super VIP"}
LeaseLivingRight = {1:"დამგირავებლის ცხოვრების უფლებით",2:"მეპატრონის ცხოვრების უფლებით"}
HasFurnitureAndTechnic = {1:"კი",2:"არა"}
RentType = {1:"მთლიანი ბინა",2:"ბინის ნაწილი",3:"ბინის ნაწილი მეპატრონესთნ ერთად"}
lease_periods = {1:"1 წელი",2:"2 წელი",3:"3 წელი",4:"4 წელი",5:"5 წელი",6:"6 წელი",7:"7 წელი",8:"8 წელი",9:"9 წელი",10:"10 წელი"}
ContractTypes = {1:"იპოთეკის ხელშეკრულება",2:"სესხის ხელშეკრულება"}
ConditionIDs = {1:"ახალი გარემონტებული",4:"მიმდინარე რემონტი",5:"სარემონტო",6:"ძველი გარემონტებული",7:"თეთრი კარკასი",8:"შავი კარკასი",9:"მწვანე კარკასი"}
price_type_ids = {0: 'სრული ფასი', 1: 'კვმ ფასი'}
booleans = {0:False, 1:True}
invese_booleans = {0: True, 1: False}
gender_ids = {1: 'მამრობითი', 2: 'მდედრობითი'}

def mapper(obj, na=0):
    return lambda x: None if x == na else obj[x] if x in obj else x

def trymap(dfSrc, dfDst, srcCol, dstCol, obj, na=0):
    dfDst[dstCol] = dfSrc[srcCol].apply(mapper(obj, na=na))

mappings = [
    ['area_size_type_id', 'area_size_type', AreaSizeTypeIDs, 0, False],
    ['yard_size_type_id', 'yard_size_type', YardSizeTypeIDs, 0, False],
    ['yard_size_type_id', 'has_yard', {0: False, 1: True, 2: True}, None, False],
    ['parking_id', 'has_parking', {0: False, 1: True, 2: True, 3: True, 4: True}, None, False],
    ['adtype_id', 'adtype', AdTypeID, 0, False],
    ['product_type_id', 'product_type', ProductTypeID, 0, False],
    ['currency_id', 'currency_code', currency_ids, 0, False],
    ['parking_id', 'parking_type', ParkingIDs, 0, False],
    ['price_type_id', 'price_type', price_type_ids, price_type_ids[0], False],
    ['estate_type_id', 'estate_type', estate_type_id, 0, False],
    ['special_persons', 'has_accessable_access', booleans, None, True],
    ['gender_id', 'user_gender', gender_ids, 0, False],
    ['canalization', 'has_wastewater', booleans, None, True],
    ['road', 'has_road', booleans, None, True],
    ['water', 'has_water', booleans, None, True],
    ['electricity', 'has_electricity', booleans, None, True]
]

mapped = pd.DataFrame(full, copy=True)
for srcCol, dstCol, obj, na, drop in mappings:
    trymap(mapped, mapped, srcCol, dstCol, obj, na=na)

srcCols = [mapping[0] for mapping in mappings if mapping[4]]
mapped = mapped.drop(columns=srcCols)\
    .drop(columns=['has_logo', 'submission_id', 'photo', 'photo_ver', 'photos_count', 'video_url']) \
    .convert_dtypes() \
    .rename(columns={"gender_id":"user_gender_id",})

column_order = [
    'title', 
    'owner_type', 
    'adtype', 
    'estate_type', 
    'product_type', 
    'price_value', 
    'currency', 
    'floor', 
    'has_parking', 
    'parking_type',
    'bedrooms', 
    'rooms', 
    'has_yard', 
    'yard_size', 
    'yard_size_type', 
    'area_size_value',
    'area_size_type' 
]
other_columns = [x for x in sorted(mapped.columns) if x not in column_order]


mapped = mapped.reindex(column_order + other_columns, axis=1)

pd.set_option('display.max_columns', None)
mapped.head()

,title,owner_type,adtype,estate_type,product_type,price_value,currency,floor,has_parking,parking_type,bedrooms,rooms,has_yard,yard_size,yard_size_type,area_size_value,area_size_type,adtype_id,amount,area_size,area_size_type_id,color,comment,currency_code,currency_id,currency_id_floor,developer_flat_id,estate_type_id,floor_floor,has_accessable_access,has_electricity,has_road,has_wastewater,has_water,homeselfie,href,l_living,lat,lng,loc_id,makler_id,makler_name,map_lat,map_lon,order_date,osm_id,owner_type_id,parent_id,parking_id,price,price_floor,price_type,price_type_id,product_type_id,street_address,user_gender,user_gender_id,user_id,username,vip,yard_size_type_id
product_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
7156153,ქირავდება დღიურად ახალი აშენებული ბინა,აგენტი,ქირავდება დღიურად,ახალი აშენებული,კორპუსის ბინა,200.0,₾,4,True,პარკინგის ადგილი,2,3,False,0,<NA>,100,მ2,7,200,100.0,1,0,ქირავდება დღიურად 3 ოთახიანი ბინა სიმონ კანდელ...,GEL,3,3,2726,1,4,False,False,False,False,False,0,https://www.myhome.ge/ka/pr/7156153/qiravdeba-...,0,41.7245209,44.7537885,647,<NA>,<NA>,41.724521,44.753788,2023-08-08 00:42:49,5469869,2,<NA>,2,200.0,200.0,სრული ფასი,0,1,სიმონ კანდელაკის ქ.,მამრობითი,1,1938385,dato.zaalishvili.81@mail.ru,0,0
7501716,ქირავდება აგარაკი,აგენტი,ქირავდება,აგარაკი,სახლი და აგარაკი,5221.2,₾,0,True,ავტოფარეხი,4,9,True,2000,მ2,300,მ2,3,"5,220",300.0,1,0,Saxli qiravdeba seqtembridan tveshi 2000$ mais...,USD,1,1,3039,18,0,False,False,False,False,False,0,https://www.myhome.ge/ka/pr/7501716/qiravdeba-...,2,41.6939085,44.6936625,675,2643,S A N D O,41.693908,44.693663,2023-08-08 02:16:25,26445392,2,3005755,1,2000.0,5221.2,სრული ფასი,0,2,,მდედრობითი,2,3005755,maka.777uchava@gmail.com,0,1
7613770,იყიდება მიწის ნაკვეთი მშენებლობისთვის,აგენტი,იყიდება,საინვესტიციო/მშენებლობისთვის,მიწის ნაკვეთი,730968.0,₾,0,False,<NA>,0,0,False,0,<NA>,650,მ2,1,"731,000",650.0,1,0,"Iyideba kerdzo saxli didi micit ,metrostan axl...",USD,1,1,3210,21,0,False,True,True,True,True,0,https://www.myhome.ge/ka/pr/7613770/iyideba-mi...,0,41.6988174,44.8818285,696,<NA>,<NA>,41.698817,44.881828,2023-08-07 17:19:34,411355289,2,<NA>,0,280000.0,730968.0,სრული ფასი,0,5,Metrostan,მდედრობითი,2,1844883,lovageorkian@gmail.com,0,0
7885912,ქირავდება ახალი აშენებული ბინა,აგენტი,ქირავდება,ახალი აშენებული,კორპუსის ბინა,5221.2,₾,3,True,ავტოფარეხი,3,4,False,0,<NA>,160,მ2,3,"5,220",160.0,1,0,"ქირავდება მთაწმინდაზე შევჩენკოს ქუჩაზე, 4 ოთახ...",USD,1,1,4430,1,3,True,False,False,False,False,0,https://www.myhome.ge/ka/pr/7885912/qiravdeba-...,0,41.6964053,44.7938526,643,7406,REAL MARKET,41.696405,44.793853,2023-08-08 17:50:26,1650325626,2,1576468,1,2000.0,5221.2,სრული ფასი,0,1,მთაწმინდა,მამრობითი,1,1576468,t.marsagishvili@mail.ru,0,0
8141073,ქირავდება ახალი აშენებული ბინა,აგენტი,ქირავდება,ახალი აშენებული,კორპუსის ბინა,5743.32,₾,3,True,პარკინგის ადგილი,3,4,False,0,<NA>,178,მ2,3,"5,740",178.0,1,0,"ქირავდება ლისი ვერანდაზე, ახალ სახლში, 4 ოთახი...",USD,1,1,5808,1,3,True,False,False,False,False,0,https://www.myhome.ge/ka/pr/8141073/qiravdeba-...,0,41.7245209,44.7537885,647,7406,REAL MARKET,41.724521,44.753788,2023-08-08 16:24:56,5469869,2,1576468,2,2200.0,5743.32,სრული ფასი,0,1,ლისი ვერანდა,მამრობითი,1,1576468,t.marsagishvili@mail.ru,0,0

In [27]:
filtered = mapped.loc[
    (mapped.owner_type_id == 1) # only owners
    & (mapped.adtype_id == 1) # only selling
    & (mapped.product_type_id == 1) #only appartments
    & (mapped.area_size_type_id == 1) #only sqm
]
filtered

,title,owner_type,adtype,estate_type,product_type,price_value,currency,floor,has_parking,parking_type,bedrooms,rooms,has_yard,yard_size,yard_size_type,area_size_value,area_size_type,adtype_id,amount,area_size,area_size_type_id,color,comment,currency_code,currency_id,currency_id_floor,developer_flat_id,estate_type_id,floor_floor,has_accessable_access,has_electricity,has_road,has_wastewater,has_water,homeselfie,href,l_living,lat,lng,loc_id,makler_id,makler_name,map_lat,map_lon,order_date,osm_id,owner_type_id,parent_id,parking_id,price,price_floor,price_type,price_type_id,product_type_id,street_address,user_gender,user_gender_id,user_id,username,vip,yard_size_type_id
product_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
9561762,იყიდება ძველი აშენებული ბინა,მესაკუთრე,იყიდება,ძველი აშენებული,კორპუსის ბინა,436779.486,₾,4,False,<NA>,3,4,False,0,<NA>,167,მ2,1,"436,800",167.31,1,0,"ვარ მეპატრონე, მაკლერებმა და სააგენტოებმა არ დ...",USD,1,1,25242,3,4,False,False,False,False,False,0,https://www.myhome.ge/ka/pr/9561762/iyideba-Zv...,0,41.7205546,44.7676099,742,<NA>,<NA>,41.720555,44.76761,2023-08-04 20:43:02,137233803,1,<NA>,0,167310.0,436779.486,სრული ფასი,0,1,ბახტრიონის ქუჩა #30,მამრობითი,1,742102,tgogoladze@inbox.ru,10,0
11270996,იყიდება ახალი აშენებული ბინა,მესაკუთრე,იყიდება,ახალი აშენებული,კორპუსის ბინა,189268.5,₾,6,False,<NA>,1,2,False,0,<NA>,53,მ2,1,"189,300",53.0,1,0,"იყიდება ბინა ახალ აშენებულ კორპუსში, ულამაზესი...",USD,1,1,1217698,1,6,True,False,False,False,False,0,https://www.myhome.ge/ka/pr/11270996/iyideba-a...,0,41.727850954152,44.723402482849,837,<NA>,<NA>,41.727851,44.723402,2023-08-08 10:02:01,79704229,1,<NA>,0,72500.0,189268.5,სრული ფასი,0,1,,მდედრობითი,2,1165336,catherine_bar@yahoo.com,0,0
12191170,იყიდება ახალი აშენებული ბინა,მესაკუთრე,იყიდება,ახალი აშენებული,კორპუსის ბინა,254925.09,₾,8,True,ავტოფარეხი,1,2,False,0,<NA>,63,მ2,1,"254,900",63.0,1,0,იყიდება ბინა 63 კვ.მ. ახალაშენებულ საცხოვრებელ...,USD,1,1,2138026,1,8,True,False,False,False,False,0,https://www.myhome.ge/ka/pr/12191170/iyideba-a...,0,41.698188924497174,44.72757351149983,752,<NA>,<NA>,41.698189,44.727574,2023-08-08 12:25:00,115834479,1,<NA>,1,97650.0,254925.09,სრული ფასი,0,1,34,მამრობითი,1,3169211,nikolozdz@gmail.com,10,0
12307718,იყიდება ახალი აშენებული ბინა,მესაკუთრე,იყიდება,ახალი აშენებული,კორპუსის ბინა,646123.5,₾,12,True,პარკინგის ადგილი,3,4,False,0,<NA>,165,მ2,1,"646,100",165.0,1,0,იყიდება ბინა 165კვ.მ. ახალაშენებულ საცხოვრებელ...,USD,1,1,2254596,1,12,False,False,False,False,False,0,https://www.myhome.ge/ka/pr/12307718/iyideba-a...,0,41.720640514107,44.706638931736,752,<NA>,<NA>,41.720641,44.706639,2023-08-08 12:24:28,115834479,1,<NA>,2,247500.0,646123.5,სრული ფასი,0,1,34,მამრობითი,1,3169211,nikolozdz@gmail.com,10,0
12881031,იყიდება ახალი აშენებული ბინა,მესაკუთრე,იყიდება,ახალი აშენებული,კორპუსის ბინა,187963.2,₾,2,False,<NA>,2,3,False,0,<NA>,80,მ2,1,"188,000",80.0,1,0,სამშენებლო კომპანია დიღომი ჰაუსი გთავაზობთ: 8...,USD,1,1,2828262,1,2,False,False,False,False,False,0,https://www.myhome.ge/ka/pr/12881031/iyideba-a...,0,41.7858421,44.7558155,4255,<NA>,<NA>,41.785842,44.755815,2023-07-10 11:57:22,308713855,1,<NA>,0,72000.0,187963.2,სრული ფასი,0,1,54,მდედრობითი,2,2069735,tatiakuprashvili@bk.ru,10,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15783218,იყიდება ძველი აშენებული ბინა,მესაკუთრე,იყიდება,ძველი აშენებული,კორპუსის ბინა,156636.0,₾,1,True,ავტოფარეხი,1,1,True,0,მ2,68,მ2,1,"156,600",68.0,1,0,<NA>,USD,1,1,5730497,3,1,False,False,False,False,False,0,https://www.myhome.ge/ka/pr/15783218/iyideba-Z...,0,41.714672969978,44.803430816981,3191,<NA>,<NA>,41.714673,44.803431,2023-08-09 00:12:43,57046491,1,<NA>,1,60000.0,156636.0,სრული ფასი,0,1,ჩანჩიბაძის 5,მამრობითი,1,4332249,lexo.com+v@gmail.com,0,1
15783221,იყიდება ახალი აშენებული ბინა,მესაკუთრე,იყიდება,ახალი აშენებული,კორპუსის ბინა,261060.0,₾,3,False,<NA>,1,2,True,0,მ2,59,მ2,1,"261,100",59.0,1,0,"კრწანისის რეზიდენციასთან, იყიდება ახალაშენებულ...",USD,1,1,5730500,1,3,True,False,False,False,False,0,https://www.myhome.ge/ka/pr/15783221/iyideba-a...,0,41.674148904507,44.811779839475,1329,<NA>,<NA>,41.674149,44.81178,2023-08-09 00:15:17,190594087,1,<NA>,0,100000.0,261060.0,სრული ფასი,0,1,კრწანისის || შესასვლელი. N19 ბინა 3,მამრობითი,1,659789,gioimedashvili@mail.ru,0,1
15783260,იყიდება ახალი აშენებული ბინა,მესაკუთრე,იყიდება,ახალი აშენებული,კორპუსის ბინა,287166.0,₾,16,False,<NA>,2,3,True,0,მ2,75,მ2,1,"287,200",75.0,1,0,<NA>,USD,1,1,5730539,1,16,False,False,False,False,False,0,https://www.myhome.ge/ka/pr/15783260/iyideba-a...,0,41.6761108,44.8481344,1242,<NA>,<NA>,41.676111,44.848134,2023-08-09 00:44:04,75280601,1,<NA>,0,110000.0,287166.0,სრული ფასი,0,1,"დირსი Dirsi , Gabriel salosis qucha",მდედრობითი,2,3229113,fabgeorgiatravel@gmail.com,0,1
15783263,იყიდება ძველი აშენებული ბინა,მესაკუთრე,იყიდება,ძველი აშენებული,კორპუსის ბინა,339378.0,₾,5,False,<NA>,3,4,False,0,<NA>,82,მ2,1,"339,400",82.35,1,0,"იყიდება 4ოთახიანი ნათელი ბინა, 3საძინებლით ( ...",USD,1,1,5730542,3,5,False,False,False,False,False,0,https://www.myhome.ge/ka/pr/15783263/iyideba-Z...,0,41.750817875256,44.762799500722,1490,<NA>,<NA>,41.750818,44.7628,2023-08-09 00:45:43,428135695,1,<NA>,0,130000.0,339378.0,სრული ფასი,0,1,,მდედრობითი,2,400599,Maia_giorgobiani@yahoo.com,0,0
15783267,იყიდება ახალი აშენებული ბინა,მესაკუთრე,იყიდება,ახალი აშენებული,კორპუსის ბინა,294997.8,₾,5,True,მიწისქვეშა პარკინგი,3,4,True,0,მ2,84,მ2,1,"295,000",84.0,1,0,"ვყიდი 4 ოთახიან ბინას,გუდვილთან ახლოს,ახალ,დას...",USD,1,1,5730546,1,5,True,False,False,False,False,0,https://www.myhome.ge/ka/pr/15783267/iyideba-a...,0,41.7858421,44.7558155,4255,<NA>,<NA>,41.785842,44.755815,2023-08-09 00:53:31,308713855,1,<NA>,3,113000.0,294997.8,სრული ფასი,0,1,,მამრობითი,1,3944846,lasurashvilimamuka4@gmail.com,0,1

In [19]:
y = filtered.price_value
y.describe()

count          21998.0
mean      211998.48806
std      969530.648679
min               15.0
25%            1566.36
50%             3915.9
75%           216679.8
max         44380200.0
Name: price_value, dtype: Float64

In [ ]:
features = [
    'title', 
    'owner_type', 
    'adtype', 
    'estate_type', 
    'product_type', 
    'price_value', 
    'currency', 
    'floor', 
    'has_parking', 
    'parking_type',
    'bedrooms', 
    'rooms', 
    'has_yard', 
    'yard_size', 
    'yard_size_type', 
    'area_size_value',
    'area_size_type' 
]